<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Examinations extends Model
{

    protected $table = 'examinations';
    protected $primaryKey = 'code_examination';
    public $timestamps = false;
    public $incrementing = false;


    public function collection()
    {
        return $this->belongsTo('App\Collections', 'code_collection');
    }

    public function toArray()
    {
        $arr = parent::toArray();
        $arr['collection'] = $this->collection; // TODO: Change the autogenerated stub
        return $arr;
    }

    protected $fillable = [
        'code_examination',
        'question',
        'code_collection',
        'answer_a',
        'answer_b',
        'answer_c',
        'answer_d',
        'answer_e',
        'answer_f',
        'answer_g',
        'answer_h',
        'answer_i',
        'answer_j',
        'answer_k',
        'answer_correct',
        'type_of_language',
        'explain_question',
        'status'
    ];

}
