<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Friends extends Model
{
    protected $table = 'friends';
    protected $primaryKey = 'code_friend';
    public $timestamps = false;
    public $incrementing = false;


    protected $fillable = [
        'code_friend',
        'friend_username',
        'username',
        'time_add',
        'accept',
    ];

    public function toArray()
    {
        $acc = parent::toArray(); // TODO: Change the autogenerated stub
        $acc_f = Account::where('username', $this->friend_username)->first();
        $account_friend = Account::where('id', $acc_f->id)->first();
        $account = Account::where('username', $this->username)->first();
        $acc['account_friend'] = $account_friend;
        $acc['account'] = $account;
        return $acc;
    }

}
