<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LikeObject extends Model
{
    protected $table = 'like_object';
    protected $primaryKey = 'code_like';
    public $timestamps = false;
    public $incrementing = false;

    protected $fillable = [
        'code_like',
        'code_object',
        'username'
    ];

    public function toArray()
    {
        $acc = parent::toArray(); // TODO: Change the autogenerated stub
        $acc['account'] = $this->account;
        return $acc;
    }

    public function account()
    {
        return $this->belongsTo('App\Account', 'username');
    }

}
