<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class NewsFeed extends Model
{
    protected $table = 'news_feed';
    protected $primaryKey = 'code_news_feeds';
    public $timestamps = false;
    public $incrementing = false;

protected $fillable = [
  'content_feeds', 'code_news_feeds', 'number_of_like', 'username', 'time_add'
];

    public function toArray()
    {
        $arr = parent::toArray(); // TODO: Change the autogenerated stub
        $arr['account'] = $this->account;
        $arr['medias'] = $this->medias;
        unset($arr['username']);
        return $arr;
    }

    public function account()
    {
        return $this->belongsTo('App\Account', 'username');
    }

    public function medias()
    {
        return $this->hasMany('App\Medias', 'code_news_feeds');
    }
}
