<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Save extends Model
{
    protected $table = 'saved';
    protected $primaryKey = 'code_save';
    public $timestamps = false;
    public $incrementing = false;


    protected $fillable = [
        'code_save',
        'code_object',
        'type_object',
        'username',
    ];

    public function toArray()
    {
        $arr = parent::toArray(); // TODO: Change the autogenerated stub
        $arr["account"] = $this->account;
        return $arr;
    }

    public function account()
    {
        return $this->belongsTo("App\Account", "username");
    }

}
