<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teams extends Model
{
    protected $table = 'teams';
    protected $primaryKey = 'code_team';
    public $timestamps = false;
    public $incrementing = false;

    protected $fillable = [
        'code_team', 'name', 'information', 'teacher', 'location'
    ];

    public function exercises()
    {
        return $this->hasMany('App\Exercise', 'code_team');
    }

    public function account()
    {
        return $this->belongsTo('App\User', 'teacher');
    }

    public function toArray()
    {
        $acc = parent::toArray(); // TODO: Change the autogenerated stub
        $acc['account'] = $this->account;
        return $acc;
    }
}
