<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teams extends Model
{
    protected $table = 'teams';
    protected $primaryKey = 'code_team';
    public $timestamps = false;
    public $incrementing = false;

    protected $fillable = [
        'code_team', 'name', 'information', 'teacher', 'location'
    ];

    public function exercises()
    {
        return $this->hasMany('App\Exercise', 'code_team');
    }

    public function account()
    {
        return $this->belongsTo('App\Account', 'teacher');
    }

    public function toArray()
    {
        $collections_name = [];
        $collections_code = [];
        $acc = parent::toArray(); // TODO: Change the autogenerated stub
        $collections = Collections::where('code_team', $this->code_team)->get();

        foreach ($collections as $c){
            array_push($collections_name, $c->name);
            array_push($collections_code, $c->code_collection);
        }

        $acc['account'] = $this->account;
        $acc['collection_count'] = count($collections);
        $acc['collections_name'] = $collections_name;
        $acc['collections_code'] = $collections_code;
        return $acc;
    }
}
